import type { Metadata } from "next";
import { poppins } from "./ui/font";
import "./globals.css";
import Nav from "@/components/Nav";
import { AuthProvider } from "../../context/AuthContext";

export const metadata: Metadata = {
    title: "CMS- Flawless",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={` ${poppins.className} antialiased`}>
                <AuthProvider>
                    <Nav />
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
